### ISSUE TITLE
perhaps you could open a dialogue with Nomadic labs to establish some devops relationship to disambiguate the user experience ?

### ISSUE THREAD

**Issue by jnorthrup** [serokell/tezos-packaging-stable#1]
![image](https://user-images.githubusercontent.com/73514/140485364-a2824de0-e3ac-475d-823c-ef7ee86095be.png)

**Comment by ixahedron** [comment]
Hi! I think 10.3.1 you're referring to is actually `v10.3-1`, i.e. 'the first version of releases based on the upstream `v10.3`'. I hope that will help you disambiguate which release you need better!

However, Serokell does not have a role in managing the tezos-dev slack. Moreover, we handle Octez releases as they come out, and can't say how long a release is likely to persist as the most current one. As such, I'm closing this issue. 

If you'd like to report another issue, please do so at the [main repository](https://github.com/serokell/tezos-packaging), as this one is just a mirror and so isn't monitored closely.
